language: scala
# Use container-based infrastructure
sudo: required
branches:
  only:
    - v3.1.3
    - master
    - /^\d\.\d+$/
    - v2.2-candidate
    - sigma454-type-check-on-script-deser
    - develop
jdk:
- openjdk9
scala:
- 2.12.8
stages:
  - test
  - name: release
    if: tag =~ ^v
  - name: snapshot
    if: "(NOT tag IS present) AND (type = push)"
jobs:
  include:
    - stage: test
      script: sbt -Denv=test clean coverage +test coverageReport && sbt coverage +test && sbt coverageReport coveralls
    - stage: release
      script: openssl aes-256-cbc -K $encrypted_dceea7e6c44e_key -iv $encrypted_dceea7e6c44e_iv
        -in ci/secring.asc.enc -out ci/secring.asc -d && gpg --import ci/secring.asc
        && sbt +ergoWallet/publishSigned sonatypeBundleRelease
    - stage: snapshot
      script: sbt +ergoWallet/publish

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
