language: scala
# Use container-based infrastructure
sudo: false
branches:
  only:
    - v2.1
    - master
    - /^\d\.\d+$/
    - v2.2-candidate
    - sigma454-type-check-on-script-deser
jdk:
- oraclejdk9
scala:
- 2.12.8
script:
  - sbt -Denv=test clean coverage test coverageReport
  - sbt -Denv=test benchmarks/compile
# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
